<a href="https://colab.research.google.com/github/LiuYunKaii/Pytorch-Tutorial/blob/main/tensors_ops.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import torch
import numpy as np

In [36]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [37]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [38]:

torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [40]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [41]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [47]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [45]:
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [42]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [46]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [48]:
# Remainder Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [50]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [51]:
# Exponents/Power
torch.pow(tensor_b, tensor_a)

tensor([   5,   36,  343, 4096])

In [52]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])