<a href="https://colab.research.google.com/github/LiuYunKaii/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.225894  , 0.91389934, 0.88896174, 0.94584224],
       [0.26254501, 0.70223577, 0.92397002, 0.34961876],
       [0.31607787, 0.24598082, 0.47168927, 0.58896435]])

In [5]:
np1.dtype

dtype('float64')

In [7]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.4782, -0.9656, -1.8993,  2.0133],
        [ 1.2860, -0.5067,  0.8581,  1.2592],
        [ 0.9066,  0.6780,  1.1614,  0.0450]])

In [10]:
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
tensor_3d.dtype

torch.float32

In [12]:
##create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2259, 0.9139, 0.8890, 0.9458],
        [0.2625, 0.7022, 0.9240, 0.3496],
        [0.3161, 0.2460, 0.4717, 0.5890]], dtype=torch.float64)